package vu.lt.mybatis.dao;

import java.util.List;
import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Purchase;

@Mapper
public interface PurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PURCHASE
     *
     * @mbg.generated Tue May 12 11:36:32 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PURCHASE
     *
     * @mbg.generated Tue May 12 11:36:32 EEST 2020
     */
    int insert(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PURCHASE
     *
     * @mbg.generated Tue May 12 11:36:32 EEST 2020
     */
    Purchase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PURCHASE
     *
     * @mbg.generated Tue May 12 11:36:32 EEST 2020
     */
    List<Purchase> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PURCHASE
     *
     * @mbg.generated Tue May 12 11:36:32 EEST 2020
     */
    int updateByPrimaryKey(Purchase record);
}