package vu.lt.mybatis.dao;

import java.util.List;
import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Store;

@Mapper
public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Tue Apr 28 19:24:00 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Tue Apr 28 19:24:00 EEST 2020
     */
    int insert(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Tue Apr 28 19:24:00 EEST 2020
     */
    Store selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Tue Apr 28 19:24:00 EEST 2020
     */
    List<Store> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Tue Apr 28 19:24:00 EEST 2020
     */
    int updateByPrimaryKey(Store record);
}